### ISSUE TITLE
[1.16.3]Regarding Tech Reborn Compatibility - Unable To Detect Ores

### ISSUE THREAD

**Issue by Lv44EnderShaman** [CumulusMC/Simple-Quern#9]
Mod List:
Fabric API: 0.24.0+build.411-1.16
Reborn Core: 4.4.2+build.73
Tech Reborn: 3.5.4+build.122
Simple Quern: v1.2.0

Launcher:
MultiMC 5, v0.6.12-develop-1481, win32-x64

Hardware Specs:
OS: Windows 7 Pro SP1, 64-bit
CPU: AMD PRO A10-7800B, 4 cores (Steamroller-Kaveri architecture)
GPU: AMD Radeon R7 (Integrated GPU)
RAM: 16 GB

I have confirmed no pre-existing issue, neither open nor closed, applies to this issue as I open it.

Issue Details:
I'm not quite sure why, but it seems that Simple Quern's compatibility with Tech Reborn and Reborn Core isn't functioning in the latest release, v1.2.0. Trying to use the Quern in an instance of Minecraft 1.16.3 with only Simple Quern, Reborn Core+Tech Reborn and Fabric API installed only allows you to grind vanilla's ores with the Diamond Handstone.

**Comment by Vaerian** [comment]
Tech Reborn compatibility is temporarily disabled because LibCD is in a weird state so conditional recipes weren't possible. We chose not to package the mod with recipes using items for other mods because without conditional recipes it would spam the log if players didn't have that other mod installed. That being said Tech Reborn support is coming later in a future update once FabricMC/fabric#1075 gets pulled in. We might also be able to release a couple datapacks to add this functionality, though it would require an extra install on the players part. Let me know what you think sounds good, I'm totally for whipping up a datapack if you think you'd get use from that.

**Comment by Lv44EnderShaman** [comment]
That actually makes a lot of sense. I hope that pull gets added, as it would put a lot less of a burden on mod authors having to package a library or dependency on LibCD. For now, I do like the idea of adding a datapack for recipe support, at least for the time being; I'm pretty good about working around JSON these days, so I can always tweak said datapack if I need to add support for other mods' ores.

**Comment by Vaerian** [comment]
Real talk, all of the recipe files are [here](https://github.com/CumulusMC/Simple-Quern/tree/1.16/src/main/resources/data/simplequern/recipes_old/compat/techreborn) we just converted formats to something like [this](https://github.com/CumulusMC/Simple-Quern/blob/1.16/src/main/resources/data/simplequern/recipes/iron_dust.json) for the last version of the mod and so they all have to be rewritten. It you're good with json the conversion isn't all that difficult, and it would actually be  a big help if you made a PR to convert them if you'd be doing it for yourself anyways.

**Comment by Lv44EnderShaman** [comment]
Well, hell, I got nothin' better to do for the rest of the night. Consider it worked on.
